spring:
  application:
    name: LBsys
  datasource:
    url: jdbc:mysql://localhost:3306/book_test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root   # 替换为您的数据库用户名
    password: 'oyjj0822' # 替换为您的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 可选：打印SQL日志
  mapper-locations: classpath:mapper/*.xml  # 指定mapper xml文件位置
  type-aliases-package: jjie.lbsystem.entity  # 实体类包路径
